/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        sans: ['-apple-system', 'BlinkMacSystemFont', '"SF Pro Display"', '"SF Pro Text"', '"Helvetica Neue"', 'Arial', 'sans-serif'],
      },
      colors: {
        apple: {
          blue:    '#0071e3',
          blue2:   '#42a5f5',
          gray:    '#6e6e73',
          silver:  '#f5f5f7',
          dark:    '#1d1d1f',
          darker:  '#000000',
          green:   '#34c759',
          red:     '#ff3b30',
          orange:  '#ff9500',
          yellow:  '#ffcc00',
          purple:  '#af52de',
          pink:    '#ff2d55',
          teal:    '#5ac8fa',
        },
        dark: {
          bg:         '#000000',
          bg2:        '#0a0a0a',
          surface1:   '#1c1c1e',
          surface2:   '#2c2c2e',
          surface3:   '#3a3a3c',
          surface4:   '#48484a',
          label1:     '#ffffff',
          label2:     '#ebebf599',
          label3:     '#ebebf54d',
          label4:     '#ebebf52e',
          separator:  '#38383a',
          opaque:     '#545458',
        },
      },
      borderRadius: {
        'apple-xs': '8px',
        'apple':    '12px',
        'apple-sm': '12px',
        'apple-md': '14px',
        'apple-lg': '18px',
        'apple-xl': '22px',
        'pill':     '9999px',
      },
      fontSize: {
        'large-title': ['34px', { lineHeight: '41px', fontWeight: '700' }],
        'title1':      ['28px', { lineHeight: '34px', fontWeight: '700' }],
        'title2':      ['22px', { lineHeight: '28px', fontWeight: '700' }],
        'title3':      ['20px', { lineHeight: '25px', fontWeight: '600' }],
        'headline':    ['17px', { lineHeight: '22px', fontWeight: '600' }],
        'body':        ['17px', { lineHeight: '22px', fontWeight: '400' }],
        'callout':     ['16px', { lineHeight: '21px', fontWeight: '400' }],
        'subhead':     ['15px', { lineHeight: '20px', fontWeight: '400' }],
        'footnote':    ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'caption1':    ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'caption2':    ['11px', { lineHeight: '13px', fontWeight: '400' }],
      },
      boxShadow: {
        'apple':         '0 2px 20px rgba(0,0,0,0.08)',
        'apple-md':      '0 4px 40px rgba(0,0,0,0.12)',
        'apple-lg':      '0 8px 60px rgba(0,0,0,0.16)',
        'apple-dark':    '0 2px 20px rgba(0,0,0,0.4)',
        'glow-blue':     '0 0 20px rgba(0,113,227,0.35)',
        'glow-green':    '0 0 20px rgba(52,199,89,0.35)',
        'glow-red':      '0 0 20px rgba(255,59,48,0.35)',
        'glow-orange':   '0 0 20px rgba(255,149,0,0.35)',
      },
      backdropBlur: { apple: '20px' },
      animation: {
        'fade-in':     'fadeIn 0.3s ease-out',
        'slide-up':    'slideUp 0.4s ease-out',
        'slide-down':  'slideDown 0.3s ease-out',
        'pulse-soft':  'pulseSoft 2s infinite',
        'shimmer':     'shimmer 1.5s infinite',
        'spin-slow':   'spin 3s linear infinite',
      },
      keyframes: {
        fadeIn:    { from: { opacity: '0' },                                      to: { opacity: '1' } },
        slideUp:   { from: { opacity: '0', transform: 'translateY(16px)' },       to: { opacity: '1', transform: 'translateY(0)' } },
        slideDown: { from: { opacity: '0', transform: 'translateY(-16px)' },      to: { opacity: '1', transform: 'translateY(0)' } },
        pulseSoft: { '0%,100%': { opacity: '1' },                                 '50%': { opacity: '0.6' } },
        shimmer:   { from: { backgroundPosition: '200% 0' },                     to:   { backgroundPosition: '-200% 0' } },
      },
    },
  },
  plugins: [],
};
